
BUNNY = 'BUNNY'
ALL_EXCHANGES = 'ALL_EXCHANGES'

EXCHANGES_LIST = [BUNNY]

CONNECTION = 'CONNECTION'
EXCHANGE = 'EXCHANGE'
RAW = 'RAW'


SQLSERVER = 'SQLSERVER'
POSTGRES = 'POSTGRES'
REDIS = 'REDIS'
API = 'API'

# REST OP
GET = 'GET'
POST = 'POST'

# available methods / tables
GET_GETCOLLECTION = 'GET_GETCOLLECTION'

# bunny API
REFRESH_VIDEO_LIBRARY = 'REFRESH_VIDEO_LIBRARY'
BUNNY_VIDEO_LIBRARY = 'BUNNY_VIDEO_LIBRARY'


# db schema
TABLE = 'tb_'
VIEW = 'vw_'