
BUNNY = 'BUNNY'
COMMON = 'COMMON'
ALL_EXCHANGES = 'ALL_EXCHANGES'

EXCHANGES_LIST = [BUNNY]

CONNECTION = 'CONNECTION'
EXCHANGE = 'EXCHANGE'
RAW = 'RAW'


SQLSERVER = 'SQLSERVER'
POSTGRES = 'POSTGRES'
REDIS = 'REDIS'
API = 'API'

# REST OP
GET = 'GET'
POST = 'POST'

# available methods / tables
GET_GETCOLLECTION = 'GET_GETCOLLECTION'

# bunny API
REFRESH_VIDEO_LIBRARY = 'REFRESH_VIDEO_LIBRARY'
BUNNY_VIDEO_LIBRARY = 'BUNNY_VIDEO_LIBRARY'
VIDEO_LIBRARY = 'VIDEO_LIBRARY'

REFRESH_VIDEO = 'REFRESH_VIDEO'
BUNNY_VIDEO = 'BUNNY_VIDEO'
VIDEO = 'VIDEO'

REFRESH_VIDEO_STREAM = 'REFRESH_VIDEO_STREAM'
BUNNY_VIDEO_STREAM = 'BUNNY_VIDEO_STREAM'
VIDEO_STREAM = 'VIDEO_STREAM'

FLOW = 'FLOW'
START_FLOW = 'START_FLOW'
END_FLOW = 'END_FLOW'



# db schema
TABLE = 'tb_'
VIEW = 'vw_'


#
VIDEOJS = 'VIDEOJS' 

STREAM_PLAY = 'STREAM_PLAY'
REFRESH_STREAM_PLAY = 'REFRESH_STREAM_PLAY'
VIDEOJS_STREAM_PLAY = 'VIDEOJS_STREAM_PLAY'
HLS_STREAM_PLAY = 'HLS_STREAM_PLAY'

CHROME = 'CHROME'
MSEDGE = 'MSEDGE'
FIREFOX = 'FIREFOX'
ALL_BROWSER=[CHROME,MSEDGE,FIREFOX]

BROWSER = 'BROWSER'
STREAM = 'STREAM'

FOLDER = 'FOLDER'

HLS = 'HLS'
DASH = 'DASH'
SINTEL = 'SINTEL'